let Data = [ 
            {'companyName' : 'Google',
            'jobTitle' : 'Front-End Developer',
            'salary' : '£20,000-£30,000',
            'exprienceNeeded' : 'Entry',
            'requiredSkills' : 'JavaScript, React.js, Redux.js',
            'logo' : '',
            'contract':'',
            'based' : 'London'},
            {'companyName' : 'Google',
            'jobTitle' : 'Back-End Developer',
            'salary' : '£20,000-£30,000',
            'exprienceNeeded' : 'Entry',
            'requiredskills' : 'JavaScript, Node.js, Express.js',
            'logo' : '',
            'contract':'',
            'based' : 'London'},
            {'companyName' : 'Google',
            'jobTitle' : 'UI & UX Designer',
            'salary' : '£35,000',
            'exprienceNeeded' : '3 Years',
            'requiredSkills' : 'Figma',
            'logo' : '',
            'contract':'',
            'based' : 'London'},
            {'companyName' : 'Google',
            'jobTitle' : 'Full Stack Developer',
            'salary' : '£35,000',
            'exprienceNeeded' : '1 year',
            'requiredSkills' : 'JavaScript, React.js, Node.js, Express.js, MangoDB',
            'logo' : '',
            'contract':'',
            'based' : 'London'},
            {'companyName' : 'Google',
            'jobTitle' : 'Dev Ops',
            'salary' : '£60,000',
            'exprienceNeeded' : '3 Years',
            'requiredSkills' : 'AWS, Google Cloud',
            'logo' : '',
            'contract':'',
            'based' : 'London'},
            {'companyName' : 'Google',
            'jobTitle' : 'Data Sciencetist',
            'salary' : '£60,000',
            'exprienceNeeded' : 'Masters in Computer Science, Maths or Physics',
            'requiredSkills' : 'Python, Java, C++',
            'logo' : '',
            'contract':'',
            'based' : 'London'},
            {'companyName' : 'Google',
            'jobTitle' : 'AI Developer',
            'salary' : '£60,000',
            'exprienceNeeded' : 'Entry',
            'requiredSkills' : 'Python, Java, C++',
            'logo' : '',
            'contract':'',
            'based' : 'London'},
            {'companyName' : 'Google',
            'jobTitle' : 'Game Developer',
            'salary' : '£30,000',
            'exprienceNeeded' : '5 Years',
            'requiredSkills' : 'C++, C#, Python',
            'logo' : '',
            'contract':'',
            'based' : 'London'},
            {'companyName' : 'Google',
            'jobTitle' : 'Front-End Developer',
            'salary' : '£45,000',
            'exprienceNeeded' : '3 Years',
            'requiredSkills' : 'JavaScript, React.js',
            'logo' : '',
            'contract':'',
            'based' : 'London'},
            {'companyName' : 'Google',
            'jobTitle' : 'Back-End Developer',
            'salary' : '£30,000',
            'exprienceNeeded' : 'Entry',
            'requiredSkills' : 'Python, Java, JavaScript',
            'logo' : '',
            'contract':'',
            'based' : 'London'},
            {'companyName' : 'Google',
            'jobTitle' : 'Full Stack Developer',
            'salary' : '£50,000',
            'exprienceNeeded' : '5 Years',
            'requiredSkills' : 'JavaScript',
            'logo' : '',
            'contract':'',
            'based' : 'London'},
            {'companyName' : 'Google',
            'jobTitle' : 'Front-End Developer',
            'salary' : '£65,000',
            'exprienceNeeded' : '5 Years',
            'requiredSkills' : 'Python, Django',
            'logo' : '',
            'contract':'',
            'based' : 'London'},
        ]





export default Data