function Data(){
    return [ 
        {id : '1',
        'companyName' : 'Google',
        'jobTitle' : 'Front-End Developer',
        'salary' : '£20,000',
        'exprienceNeeded' : 'Entry',
        'requiredSkills' : 'JavaScript, React.js, Redux.js',
        'logo' : '',
        'contract':'',
        'based' : 'London'},
        { id : '2',
        'companyName' : 'Google',
        'jobTitle' : 'Back-End Developer',
        'salary' : '£30,000',
        'exprienceNeeded' : 'Entry',
        'requiredskills' : 'JavaScript, Node.js, Express.js',
        'logo' : '',
        'contract':'',
        'based' : 'London'},
        {id : '3',
        'companyName' : 'Google',
        'jobTitle' : 'UI & UX Designer',
        'salary' : '£35,000',
        'exprienceNeeded' : '3 Years',
        'requiredSkills' : 'Figma',
        'logo' : '',
        'contract':'',
        'based' : 'London'},
        {id: '4',
        'companyName' : 'Google',
        'jobTitle' : 'Full Stack Developer',
        'salary' : '£35,000',
        'exprienceNeeded' : '1 year',
        'requiredSkills' : 'JavaScript, React.js, Node.js, Express.js, MangoDB',
        'logo' : '',
        'contract':'',
        'based' : 'London'},
        {id: '5',
        'companyName' : 'Google',
        'jobTitle' : 'Dev Ops',
        'salary' : '£60,000',
        'exprienceNeeded' : '3 Years',
        'requiredSkills' : 'AWS, Google Cloud',
        'logo' : '',
        'contract':'',
        'based' : 'London'},
        {id : '6',
        'companyName' : 'Google',
        'jobTitle' : 'Data Sciencetist',
        'salary' : '£60,000',
        'exprienceNeeded' : 'Masters in Computer Science, Maths or Physics',
        'requiredSkills' : 'Python, Java, C++',
        'logo' : '',
        'contract':'',
        'based' : 'London'},
        {id : '7',
        'companyName' : 'Google',
        'jobTitle' : 'AI Developer',
        'salary' : '£60,000',
        'exprienceNeeded' : 'Entry',
        'requiredSkills' : 'Python, Java, C++',
        'logo' : '',
        'contract':'',
        'based' : 'London'},
        {id : '8',
        'companyName' : 'Google',
        'jobTitle' : 'Game Developer',
        'salary' : '£30,000',
        'exprienceNeeded' : '5 Years',
        'requiredSkills' : 'C++, C#, Python',
        'logo' : '',
        'contract':'',
        'based' : 'London'},
        {id : '9',
        'companyName' : 'Google',
        'jobTitle' : 'Front-End Developer',
        'salary' : '£45,000',
        'exprienceNeeded' : '3 Years',
        'requiredSkills' : 'JavaScript, React.js',
        'logo' : '',
        'contract':'',
        'based' : 'London'},
        {id : '10',
        'companyName' : 'Google',
        'jobTitle' : 'Back-End Developer',
        'salary' : '£30,000',
        'exprienceNeeded' : 'Entry',
        'requiredSkills' : 'Python, Java, JavaScript',
        'logo' : '',
        'contract':'',
        'based' : 'London'},
        {id : '11',
        'companyName' : 'Google',
        'jobTitle' : 'Full Stack Developer',
        'salary' : '£50,000',
        'exprienceNeeded' : '5 Years',
        'requiredSkills' : 'JavaScript',
        'logo' : '',
        'contract':'',
        'based' : 'London'},
        {id : '12',
        'companyName' : 'Google',
        'jobTitle' : 'Front-End Developer',
        'salary' : '£65,000',
        'exprienceNeeded' : '5 Years',
        'requiredSkills' : 'Python, Django',
        'logo' : '',
        'contract':'',
        'based' : 'London'},
    ]
}  





export default Data